### ISSUE TITLE
TST: Azure Pipelines is failing

### ISSUE THREAD

**Issue by pllim** [astropy/extension-helpers#15]
Red badge!

It is complaining about `LINK : fatal error LNK1158: cannot run 'rc.exe'` or one `.h` file or another, depending on which job you are looking at.

**Comment by astrofrog** [comment]
Looks like this was a transient issue, it's all green now.

**Comment by pllim** [comment]
Huh!!! Sure lasted a long time for something transient. Thanks for looking into this!
