### ISSUE TITLE
TST: Need a cron job on Azure Pipelines

### ISSUE THREAD

**Issue by pllim** [astropy/extension-helpers#20]
Now the badge says "never built," which implies that the CI has not run in a while. Needs a cron job to ensure upstream changes don't break tests.

**Comment by astrofrog** [comment]
I just added one in https://github.com/astropy/extension-helpers/commit/bf34860076d8b774d1fa3de391b5ef1252089f0e, let's see if it works! (should be triggered on Sunday at midnight UTC)

**Comment by pllim** [comment]
Thanks!

**Comment by astrofrog** [comment]
@pllim @Cadair - just FYI the Azure UI does show the next scheduled build for 24th May at midnight UTC so I think we're all good. Glad it's this easy!

**Comment by pllim** [comment]
If it fails, who gets notified? 🤔

**Comment by astrofrog** [comment]
I think I get an email. We'll find out!
