### ISSUE TITLE
Migrate away from any direct distutils usage

### ISSUE THREAD

**Issue by Cadair** [astropy/extension-helpers#31]
https://www.python.org/dev/peps/pep-0632/ Deprecates distutils in Python 3.10 and will remove it in 3.12 we need to stop using distutils before then.

**Comment by astrofrog** [comment]
This might also be a good opportunity to see if we want to just deprecate certain things

**Comment by Cadair** [comment]
We should probably do this sooner rather than later so we can have some longer deprecation times and avoid too many warnings.

**Comment by astrofrog** [comment]
Yes, agree!

**Comment by astrofrog** [comment]
Done in https://github.com/astropy/extension-helpers/pull/34
