### ISSUE TITLE
Ideas for allowing usage without setup.py

### ISSUE THREAD

**Issue by astrofrog** [astropy/extension-helpers#32]
I've been thinking into whether we can try and make it so that using setup.py is not required - one possible option to investigate would be to make use of https://setuptools.pypa.io/en/latest/userguide/extension.html#customizing-distribution-options to add extensions to the Distribution object. Since all that extension-helpers really does is:

```
from extension_helpers import get_extensions
...
setup(..., ext_modules=get_extensions())
```

why not simply use the entry point above and assign ``Distribution.ext_modules``?

**Comment by Cadair** [comment]
I think with this approach `extension_helpers` could have as many or as few setup.cfg sections as we want, so I see no reason why we couldn't come up with a scheme which works?

**Comment by astrofrog** [comment]
#33 has been merged and supports enabling extension-helpers via setup.cfg with no changes required to ``setup_package.py`` files!
