### ISSUE TITLE
Consider removing support of ``--compiler`` option to ``setup.py``

### ISSUE THREAD

**Issue by astrofrog** [astropy/extension-helpers#35]
I think most people override the compiler with environment variables? This would be a breaking change but gets rid of a bunch of code in ``_distutils_helpers.py``

**Comment by Cadair** [comment]
I don't really follow what you are proposing here, we should support env vars or we should support CLI flags?

**Comment by astrofrog** [comment]
Let me open a PR to show :)

**Comment by astrofrog** [comment]
There was a critical word missing in the title :laughing: 

PR here: https://github.com/astropy/extension-helpers/pull/36

**Comment by Cadair** [comment]
ah that one pesky word does make it a little clearer!!

**Comment by astrofrog** [comment]
Done in #36
