### ISSUE TITLE
Release on PyPI from time to time?

### ISSUE THREAD

**Issue by gdurif** [astropy/extension-helpers#38]
Hi, the github repository is still active, which is great (thanks by the way), for there has not been any release on PyPI since december 2019. Is it a deliberated choice? If not, would that be possible to update the PyPI repository from time to time (it would facilitate requiring `extension-helpers` in other package setup).
Thanks

**Comment by Cadair** [comment]
We have recently been working on some larger changes (hence the activity) once we have them finalised I am sure we will be doing a release.

Is there anything we have merged since the last release you want to rely on?

**Comment by gdurif** [comment]
Thanks for your reply (and for the work you put into this :smiley: )

I mainly want to use [OpenMP helpers](https://extension-helpers.readthedocs.io/en/latest/openmp.html). I did not check if there was any modification regarding this specific feature since version 0.1

**Comment by Cadair** [comment]
I am reasonably sure they are in 0.1, I think we can probably cook a release with the removal of distutils and no-setup.py support soon though. @astrofrog ?

**Comment by gdurif** [comment]
Ok, thank you very much :+1:

**Comment by astrofrog** [comment]
@Cadair - yes once #37 is in I think we should just go ahead and release (we shouldn't wait for #26 as it might require a bit more work)

**Comment by astrofrog** [comment]
@gdurif - extension-helpers 1.0.0 has been released today!

**Comment by gdurif** [comment]
@astrofrog Thanks! That's great. FYI, we are now using `extension-helpers` as a requirement for our own package.
