### ISSUE TITLE
Support for `pyproject.toml` configuration

### ISSUE THREAD

**Issue by WilliamJamieson** [astropy/extension-helpers#47]
In this https://github.com/astropy/astropy/pull/14361#issuecomment-1419210239, it was requested that `extension-helpers` support something like:

```ini
[extension-helpers]
use_extension_helpers = true
```

configurations, but in the `pyproject.toml` instead of the `setup.cfg`. This is so that projects like `astropy` can move towards adopting [PEP621](https://peps.python.org/pep-0621/) (storing all project metadata in `pyproject.toml` instead of across the `setup.cfg` and `setup.py` files).

**Comment by WilliamJamieson** [comment]
Note, if there are no objections to adding this as an option, I'll give it a shot.

**Comment by astrofrog** [comment]
No objections from me as long as it doesn't add too much complexity.

**Comment by WilliamJamieson** [comment]
I think it would just require a (possibly optional) dependency on `tomli` for python < 3.11 (enough of `tomli` is part of python 3.11 for it to work).

**Comment by astrofrog** [comment]
That seems reasonable
