### ISSUE TITLE
Drop support for older versions of python

### ISSUE THREAD

**Issue by WilliamJamieson** [astropy/extension-helpers#49]
Looks like this project is still testing against python 3.6, which I don't think is supported by the github CI runners for ubuntu anymore. This will make testing more difficult as time progresses.

While we are at it should python 3.7 support be dropped as well? The main `astropy` project has already dropped it.

**Comment by Cadair** [comment]
I would rather be conservative with Python versions for this project, but I think dropping 3.6 at this point would be fine.

**Comment by WilliamJamieson** [comment]
Also, should python 3.9, 3.10, and 3.11 CI jobs be added?

**Comment by Cadair** [comment]
yes please.
